  // Calibrate();
  // Forward(1, 60);
  // RollerRoller.spinFor(vex::reverse, 0.35, rotationUnits::rev);
  // Back(4, 60);
  // Left(135, 20);
  // Intake.spin(fwd, 10, volt);
  // Forward(50, 60);
  // Left(100, 20);
  // Back(20, 60);
  // Launch();
  // Intake.spinFor(vex::reverse, 5, rotationUnits::rev);
  // Forward(7, 60);